spring.application.name=springboot-fullstack

management.endpoints.web.exposure.include=health,info
management.info.env.enabled= true

# reduce logging level : set logging level to warn. Only shows errors and warns.
logging.level.root=warn
logging.level.org.springframework.security = debug

# Adding logging configs to display SQL statements
logging.level.org.hibernate.sql= debug
logging.level.org.hibernate.orm.jdbc.bind= trace